# Generated by Django 4.2.2 on 2023-08-12 11:21

import tinymce.models
import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationalPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='Course/', verbose_name='Image')),
                (
                    'ppoi',
                    versatileimagefield.fields.PPOIField(
                        default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'
                    ),
                ),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='Feature/', verbose_name='Image')),
                (
                    'ppoi',
                    versatileimagefield.fields.PPOIField(
                        default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'
                    ),
                ),
                ('order', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'platform',
                    models.CharField(
                        choices=[
                            ('facebook', 'Facebook'),
                            ('twitter', 'Twitter'),
                            ('linkedin', 'Linkedin'),
                            ('instagram', 'Instagram'),
                        ],
                        max_length=20,
                    ),
                ),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='Team/', verbose_name='Image')),
                (
                    'ppoi',
                    versatileimagefield.fields.PPOIField(
                        default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'
                    ),
                ),
                ('role', models.CharField(max_length=255)),
                ('order', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='WeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('order', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={'ordering': ['order']},
        ),
    ]
