# Generated by Django 4.2.2 on 2023-08-12 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('web', '0001_initial')]

    operations = [
        migrations.AlterModelOptions(
            name='educationalprograms', options={'verbose_name_plural': 'Educational Programs'}
        ),
        migrations.AlterModelOptions(name='weoffer', options={'verbose_name_plural': 'We Offer'}),
    ]
