# Generated by Django 5.0 on 2023-12-21 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('web', '0002_alter_educationalprograms_options_and_more')]

    operations = [
        migrations.AlterModelOptions(name='weoffer', options={'ordering': ['order'], 'verbose_name_plural': 'We Offer'})
    ]
