# Generated by Django 5.0 on 2024-01-09 14:41

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0003_alter_weoffer_options')]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='Team/', verbose_name='Image')),
            ],
        )
    ]
