# Generated by Django 5.0 on 2024-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0004_magazine')]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(name='Magazine'),
    ]
