# Generated by Django 5.0 on 2024-01-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0005_book_delete_magazine')]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name='Book'),
    ]
